apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/scott-lew/gke-testing-lab.git
    targetRevision: HEAD
    path: argocd/argocd-testapp
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-testapp